### ISSUE TITLE
Namespace variables

### ISSUE THREAD

**Issue by vitalbone** [dvbsknd/freeCodeCamp-frontEndProjects#1]
> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- [Martin Fowler quoting Phil Karlton](https://martinfowler.com/bliki/TwoHardThings.html)

In this case, a worthy fix is to namespace the concepts:

https://github.com/dvbsknd/freeCodeCamp-frontEndProjects/blob/eec107c94008e5eee81b0eb59be6cf9b43098b22/challenges/pomodoro-clock/app.js#L38

**`STATE` can become `CLOCK_STATE`**

https://github.com/dvbsknd/freeCodeCamp-frontEndProjects/blob/eec107c94008e5eee81b0eb59be6cf9b43098b22/challenges/pomodoro-clock/app.js#L46

**`MODE` can become `CLOCK_MODE`**

**Comment by dvbsknd** [comment]
@vitalbone! Thank you. Always value your input/output.

**Comment by dvbsknd** [comment]
I was also thinking that perhaps I should store those concepts in a single state object so that `useEffect` isn't run multiple times per clock-cycle, ie. a few different state changes happen every second, which I think fires `useEffect` each time. So far it hasn't caused any bugs but in theory I think it could. Do you have any thoughts on that? It's "cleaner" to have each state in its own `useState` variable, but maybe that's overkill.

**Comment by vitalbone** [comment]
I like that idea. Have a go at #6 first and then migrate the multiples states into one object.

**Comment by dvbsknd** [comment]
Good call.
