### ISSUE TITLE
Break up controlClock into separate handlers

### ISSUE THREAD

**Issue by vitalbone** [dvbsknd/freeCodeCamp-frontEndProjects#6]
https://github.com/dvbsknd/freeCodeCamp-frontEndProjects/blob/eec107c94008e5eee81b0eb59be6cf9b43098b22/challenges/pomodoro-clock/app.js#L207

There's no need to encapsulate all the logic in one function. It can be separated into multiple handlers. For example:

```js
const handleDecrement = () => ({state , breakLength}) => {
  let newTime = breakLength <= 60 ? 60 : breakLength - 60;
  if (state === STATE.stopped) changeBreak(newTime);
}

<button type='button' id='break-decrement' onClick={handleDecrement({state, breakLength})}>
  <i className="fas fa-arrow-alt-circle-left"></i>
</button>
```

BTW

```js
const handleDecrement = () => ({state , breakLength}) => {

// is equivalent to 
function handleDecrement({state , breakLength}) {

// if
<button type='button' id='break-decrement' onClick={() => handleDecrement({state, breakLength})}>

// we just 'curry' the first function invocation.
```

**Comment by dvbsknd** [comment]
Also great feedback. I'll take this into account.

**Comment by dvbsknd** [comment]
A couple of quick questions on this one!

1. It seems like when I use the "currying" pattern of `const handleDecrement = () => ({state , breakLength}) => {` then `state` and `breakLength` are undefined in my function, but `const handleDecrement = ({state , breakLength}) => () => {` works. Is that right?
1. One of my controls is an input where the user can type the expected break length rather than just use the arrows to toggle it. What's the best way to access the value of that field in this scenario, ie. where do I pass the event object?

<img width="269" alt="Screenshot 2020-08-03 08 50 29" src="https://user-images.githubusercontent.com/1005395/89134200-71274180-d566-11ea-9902-cd7674eb3e5e.png">

**Comment by vitalbone** [comment]
1. Ah yes, that makes sense - got the order of the function invocations around the wrong way.
2. Sounds like the value should be part of your app state - something like `breakValue`. Similar to most "counter" examples like https://reactjs.org/docs/hooks-state.html

**Comment by dvbsknd** [comment]
> Sounds like the value should be part of your app state

Not sure if I totally follow it—it already is, but if I want to modify it I need to send the handler the new value that the user typed in. I can't seem to access the event object but I'm sure I can work it out, don't worry!

**Comment by vitalbone** [comment]
Oh right, you need to access the user input value. Could you extract it from a native input method like `onKeyPress` or `onBlur` (or something similar) on the input and pass that in?

**Comment by dvbsknd** [comment]
I'll just write a separate function to handle the `onChange` for that input, I think.

**Comment by vitalbone** [comment]
Yeah that could do it!
